<a href="https://colab.research.google.com/github/sarah-whitin/pytorch_tutorial/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# Lists

In [2]:
my_list = [[1,2,3,4],[5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

# Numpy arrays

Codemy.com has a tutorial - NumPy for ML

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.21964373, 0.03631779, 0.22609939, 0.26136518],
       [0.26258477, 0.40831232, 0.09856002, 0.576912  ],
       [0.87477831, 0.5970277 , 0.37289346, 0.8221963 ]])

In [4]:
np1.dtype

dtype('float64')

# Tensors

* A torch. tensor is a mulitdimensional matrix containing elements of a single data type
* similiar to numpy arrays, but full of fun things that make them work better on GPU (vs regular CPUs)
* default data type of float32
* more suitable for deep learning than a numpy array

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.3265,  1.1829,  0.7286,  1.0218],
        [-0.4969,  0.0980,  0.6749,  1.9212],
        [-0.7023,  0.6213,  1.0967, -1.6242]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor #not that it changed float32 into floar64

tensor([[0.2196, 0.0363, 0.2261, 0.2614],
        [0.2626, 0.4083, 0.0986, 0.5769],
        [0.8748, 0.5970, 0.3729, 0.8222]], dtype=torch.float64)

# Tensor operations

In [8]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_torch2 = my_torch2.reshape(2,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
my_torch3 = torch.arange(10)
print(my_torch3)
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
my_torch5 = torch.arange(10)
my_torch6 = my_torch5.reshape(2,5)
print(my_torch5)
print(my_torch6)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [29]:
my_torch5[1] = 4141
print(my_torch5)
print(my_torch6)

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])
tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [31]:
# Slices
# Grab a specific item
my_torch7 = torch.arange(10)
my_torch7[7]

tensor(7)

In [32]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [34]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [35]:
# return colomn
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# Tensor Math

In [40]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [41]:
# Addition Short-Hand
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [42]:
# Addition Long-Hand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [45]:
# Subtraction
print(tensor_a - tensor_b)

# Subtraction Long-Hand
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])


tensor([-4, -4, -4, -4])

In [48]:
# Multiplication
print(tensor_a * tensor_b)

# Multiplication Long-Hand
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])


tensor([ 5, 12, 21, 32])

In [50]:
# Division
tensor_a / tensor_b # converts to float

# Division Long-Hand
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [53]:
# Remainders
print(tensor_b % tensor_a)

# Remainders Long-Hand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [56]:
# Exponents / Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [57]:
# Another way to do long-hands
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [58]:
# Re-assignment
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)
tensor_b

tensor([5, 6, 7, 8])